### ISSUE TITLE
Getting "no sig provided by module (err: __)" for both release types.

### ISSUE THREAD

**Issue by dlamkins** [blish-hud/arcdps-bhud#1]
Using v0.2.2 and ArcDps released 2019-06-11.

Using the GNU compiled module, I got the following error after launching GW2:
![image](https://user-images.githubusercontent.com/1950594/60750305-ac76cb80-9f74-11e9-9212-e2967e9f94d6.png)

Using the MSVC compiled module, I got the following error after launching GW2:
![image](https://user-images.githubusercontent.com/1950594/60750316-cfa17b00-9f74-11e9-8f74-12b45a3b127f.png)

A log was created as `P:\Guild Wars 2\addons\bhud\errors.log` but nothing is written.

Are there any dependencies or steps that I might be missing?

**Comment by greaka** [comment]
fixed in release 0.2.3
thanks for the report
